{% set name = "pymdown-extensions" %}
{% set version = "9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01e4bec7f4b16beaba0087a74496401cf11afd69e3a11fe95cb593e5c698ef40

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - markdown >=3.2
    - python >=3.6

test:
  imports:
    - pymdownx

about:
  home: https://github.com/facelessuser/pymdown-extensions
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Extension pack for Python Markdown.
  doc_url: https://facelessuser.github.io/pymdown-extensions/
  dev_url: https://github.com/facelessuser/pymdown-extensions

extra:
  recipe-maintainers:
    - monaldoj
    - ewels
    - maxibor
