{% set name = "pymdown-extensions" %}
{% set version = "10.20.1" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/p/pymdown_extensions/pymdown_extensions-{{ version }}.tar.gz
  sha256: e7e39c865727338d434b55f1dd8da51febcffcaebd6e1a0b9c836243f660740a

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=0.21.1
  run:
    - python >={{ python_min }}
    - markdown >=3.6
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - pymdownx

about:
  home: https://github.com/facelessuser/pymdown-extensions
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Extension pack for Python Markdown.
  doc_url: https://facelessuser.github.io/pymdown-extensions/
  dev_url: https://github.com/facelessuser/pymdown-extensions

extra:
  recipe-maintainers:
    - dhirschfeld
    - monaldoj
    - ewels
    - maxibor
