{% set name = "pymdown-extensions" %}
{% set version = "10.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # FIXME:
  # The above url did not work for version 9.4.
  # If it works in future it should be used in preference to the GitHub archive url below.
  url: https://github.com/facelessuser/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9b09706eb656ff4ea1263664df9bceb14ac84f034e5dc68142853cb63fcf17c3

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=0.21.1
  run:
    - python >={{ python_min }}
    - markdown >=3.6
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - pymdownx

about:
  home: https://github.com/facelessuser/pymdown-extensions
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Extension pack for Python Markdown.
  doc_url: https://facelessuser.github.io/pymdown-extensions/
  dev_url: https://github.com/facelessuser/pymdown-extensions

extra:
  recipe-maintainers:
    - dhirschfeld
    - monaldoj
    - ewels
    - maxibor
